### ISSUE TITLE
Upload tar.gz for sdist

### ISSUE THREAD

**Issue by koobs** [ployground/ploy_ezjail#6]
One less dependency in the FreeBSD port

<3

**Comment by tomster** [comment]
sorry, i don't know what you mean with that. care to elaborate? :)

**Comment by fschulze** [comment]
We (I) upload zips, not tar.gz. Since I use a tool for the uploads which doesn't create tar.gz, it's not trivial for me to create and upload tar.gz though.

**Comment by koobs** [comment]
@tomster Yah, as @fschulze mentioned, its regarding: https://docs.python.org/2/distutils/sourcedist.html

Having a tar.gz version of the sdist (you can upload multiple ones) will allow me to remove a dependency (unzip) from the bsdploy and py-ploy* ports

**Comment by fschulze** [comment]
Done.
